### ISSUE TITLE
Поддержка вывода в формате helm

### ISSUE THREAD

**Issue by kafnevod** [alt-cloud/podman-compose-to-kube#3]
> Все описанные ниже файлы находятся в ветке feature-helm проекта

## Добавление значения флага --type(-t)
Для вывода стека сервисов в формате `helm` для флага `--type(-t)` добавляется значение `helm(h)`

## Формат каталога helm-шаблонов

helm-шаблоны располагаются в каталоге [hemltemplates](https://github.com/alt-cloud/podman-compose-to-kube/tree/feature-helm/hemltemplates).

Каждая api-версия размещается в отдельном каталоге. Текущая версия располагается в каталоге [v2](https://github.com/alt-cloud/podman-compose-to-kube/tree/feature-helm/hemltemplates/v2).
Он содержит дерево файлов, сформированный командой 
```
helm create .
```
Текущая версия содержит файлы:
```
├── charts
├── Chart.yaml
├── templates
│   ├── deployment.yaml
│   ├── _helpers.tpl
│   ├── hpa.yaml
│   ├── ingress.yaml
│   ├── NOTES.txt
│   ├── serviceaccount.yaml
│   ├── service.yaml
│   └── tests
│       └── test-connection.yaml
└── values.yaml
```
На основе данного дерева формируются поддеревья разворачивания сервисов.
Для нашего примера это поддеревья:
- [redis](https://github.com/alt-cloud/podman-compose-to-kube/tree/feature-helm/tests/helm/manifests/default/counter/Helm/charts/redis)
-  [web](https://github.com/alt-cloud/podman-compose-to-kube/tree/feature-helm/tests/helm/manifests/default/counter/Helm/charts/web) 

### Уровень описания Deployments

Дерево файлов helm формируется в каталоге
```
<manifests_directory>
└── <namespace>
    └── Helm
        └── <project>
```
В нашем случае это каталог 
```
manifests/
└── default
    └── Helm
        └── counter
```
В данном каталоге создаются:
- подкаталог `charts`, содержащий шаблоны (templates) `deployments` , в нашем случае `redis`, `web`;
- файл `Chart.yaml` описания  `deployments`;
- файл `values.yaml` описания переменных шаблонов `deployments`;
```
manifests/
└── default
    └── Helm
        └── counter
            ├── charts
            │   ├── redis
            │   └── web
            ├── Chart.yaml
            └── values.yaml
```
Файл `Charts.yaml` содержит описание `deployments` :
```
apiVersion: v2
name: counter
description: A Helm chart for <projects_name>
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: <deployment1_name>
    version: "0.1.0"
    repository: "file://./<depploymenet1_catalog>"
    enabled: true
  - name: <deployment2_name>
    version: "0.1.0"
    repository: "file://./<depploymenet2_catalog>"
    enabled: true
  - ...
```
В нашем случае файл содержит:
```
apiVersion: v2
name: counter
description: A Helm chart for hello-python
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: web
    version: "0.1.0"
    repository: "file://./web"
    enabled: true
  - name: redis
    version: "0.1.0"
    repository: "file://./redis"
    enabled: true
```

Файл `values.yaml` содержит описание переменных шаблонов (`templates`) в каталогах `charts/<имя_deployment>`. Они перекравают значения переменных, описанных в файлах `charts/<имя_deployment>/values.yaml`
